/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.event.ActionListener;

/**
 *
 * @author Izzan (local)
 */
public class HomePanel extends javax.swing.JFrame {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelIdPegawai = new javax.swing.JLabel();
        labelNamaPegawai = new javax.swing.JLabel();
        tfIdPegawai = new javax.swing.JTextField();
        tfNamaPegawai = new javax.swing.JTextField();
        panelTollCard = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tfIdCard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonConfirmIsi = new javax.swing.JButton();
        bCheckSaldoCard = new javax.swing.JButton();
        cbVoucher = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        textIdCard = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bCheckTollCard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelKtp = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelHp = new javax.swing.JLabel();
        buttonNewCard = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelIdPortal = new javax.swing.JLabel();
        labelTarif = new javax.swing.JLabel();
        buttonNewPortal = new javax.swing.JButton();
        buttonEditPortal = new javax.swing.JButton();
        buttonDeletePortal = new javax.swing.JButton();
        bCheckPortal = new javax.swing.JButton();
        tfNamaPortal = new javax.swing.JTextField();
        bBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Toll Card App");

        labelIdPegawai.setText("ID Pegawai : ");

        labelNamaPegawai.setText("Nama : ");

        tfIdPegawai.setEditable(false);

        tfNamaPegawai.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNamaPegawai)
                    .addComponent(labelIdPegawai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIdPegawai)
                    .addComponent(tfNamaPegawai))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdPegawai)
                            .addComponent(tfIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamaPegawai)
                            .addComponent(tfNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("Toll ID Card");

        jLabel3.setText("Voucher (Rp)");

        buttonConfirmIsi.setText("Confirm");

        bCheckSaldoCard.setText("Check");

        cbVoucher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10000", "20000", "50000", "100000" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(tfIdCard))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCheckSaldoCard)
                    .addComponent(buttonConfirmIsi))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCheckSaldoCard))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(buttonConfirmIsi)
                .addContainerGap())
        );

        panelTollCard.addTab("Isi Saldo Toll Card", jPanel2);

        jLabel4.setText("Toll ID Card");

        bCheckTollCard.setText("Check");

        jLabel5.setText("No. KTP");

        jLabel6.setText("Nama");

        jLabel7.setText("Alamat");

        jLabel8.setText("No. HP");

        labelKtp.setText("-");

        labelNama.setText("-");

        labelAlamat.setText("-");

        labelHp.setText("-");

        buttonNewCard.setText("New Toll Card");
        buttonNewCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewCardActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete Card");

        buttonEdit.setText("Edit Profile");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        jLabel9.setText("Saldo (Rp)");

        labelSaldo.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonNewCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(buttonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(labelHp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(41, 41, 41)
                                .addComponent(labelAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(textIdCard, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bCheckTollCard))
                                    .addComponent(labelKtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(24, 24, 24)
                                .addComponent(labelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCheckTollCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelKtp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelHp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewCard)
                    .addComponent(buttonDelete)
                    .addComponent(buttonEdit))
                .addContainerGap())
        );

        panelTollCard.addTab("Toll Card", jPanel3);

        jLabel10.setText("Nama Portal");

        jLabel11.setText("Id Portal");

        jLabel12.setText("Tarif (Rp)");

        labelIdPortal.setText("-");

        labelTarif.setText("-");

        buttonNewPortal.setText("New Portal");
        buttonNewPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewPortalActionPerformed(evt);
            }
        });

        buttonEditPortal.setText("Edit Portal");
        buttonEditPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditPortalActionPerformed(evt);
            }
        });

        buttonDeletePortal.setText("Delete Portal");
        buttonDeletePortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletePortalActionPerformed(evt);
            }
        });

        bCheckPortal.setText("Check");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelIdPortal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(labelTarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfNamaPortal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCheckPortal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonNewPortal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(buttonEditPortal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeletePortal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNamaPortal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCheckPortal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelIdPortal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelTarif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewPortal)
                    .addComponent(buttonDeletePortal)
                    .addComponent(buttonEditPortal))
                .addContainerGap())
        );

        panelTollCard.addTab("Toll Portal", jPanel4);

        bBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTollCard, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTollCard, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewCardActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonNewPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewPortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewPortalActionPerformed

    private void buttonEditPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditPortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditPortalActionPerformed

    private void buttonDeletePortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletePortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeletePortalActionPerformed

    /**
     * @param args the command line arguments
     */
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCheckPortal;
    private javax.swing.JButton bCheckSaldoCard;
    private javax.swing.JButton bCheckTollCard;
    private javax.swing.JButton buttonConfirmIsi;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeletePortal;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonEditPortal;
    private javax.swing.JButton buttonNewCard;
    private javax.swing.JButton buttonNewPortal;
    private javax.swing.JComboBox cbVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelHp;
    private javax.swing.JLabel labelIdPegawai;
    private javax.swing.JLabel labelIdPortal;
    private javax.swing.JLabel labelKtp;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaPegawai;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTarif;
    private javax.swing.JTabbedPane panelTollCard;
    private javax.swing.JTextField textIdCard;
    private javax.swing.JTextField tfIdCard;
    private javax.swing.JTextField tfIdPegawai;
    private javax.swing.JTextField tfNamaPegawai;
    private javax.swing.JTextField tfNamaPortal;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getbCheckPortal() {
        return bCheckPortal;
    }
    public javax.swing.JButton getbCheckSaldoCard() {
        return bCheckSaldoCard;
    }
    public javax.swing.JButton getbCheckTollCard() {
        return bCheckTollCard;
    }
    public javax.swing.JButton getButtonConfirmIsi() {
        return buttonConfirmIsi;
    }
    public javax.swing.JButton getButtonDeletePortal() {
        return buttonDeletePortal;
    }
    public javax.swing.JButton getButtonEdit() {
        return buttonEdit;
    }
    public javax.swing.JButton getButtonEditPortal() {
        return buttonEditPortal;
    }
    public javax.swing.JButton getButtonNewCard() {
        return buttonNewCard;
    }
    public javax.swing.JButton getButtonNewPortal() {
        return buttonNewPortal;
    }
    public javax.swing.JLabel getLabelAlamat() {
        return labelAlamat;
    }
    public javax.swing.JLabel getLabelHp() {
        return labelHp;
    }
    public javax.swing.JLabel getLabelIdPegawai() {
        return labelIdPegawai;
    }
    public javax.swing.JLabel getLabelIdPortal() {
        return labelIdPortal;
    }
    public javax.swing.JLabel getLabelKtp() {
        return labelKtp;
    }
    public javax.swing.JLabel getLabelNama() {
        return labelNama;
    }
    public javax.swing.JLabel getLabelNamaPegawai() {
        return labelNamaPegawai;
    }
    public javax.swing.JLabel getLabelSaldo() {
        return labelSaldo;
    }
    public javax.swing.JLabel getLabelTarif() {
        return labelTarif;
    }
    public javax.swing.JTabbedPane getPanelTollCard() {
        return panelTollCard;
    }
    public javax.swing.JTextField getTextIdCard() {
        return textIdCard;
    }
    public javax.swing.JTextField getTfIdCard() {
        return tfIdCard;
    }
    public javax.swing.JTextField getTfNamaPortal() {
        return tfNamaPortal;
    }
    public javax.swing.JButton getButtonDelete() {
        return buttonDelete;
    }
    public javax.swing.JComboBox getCbVoucher() {
        return cbVoucher;
    }
    public void addListener(ActionListener e){
        bCheckPortal.addActionListener(e);
        bCheckSaldoCard.addActionListener(e);
        bCheckTollCard.addActionListener(e);
        buttonConfirmIsi.addActionListener(e);
        getButtonDelete().addActionListener(e);
        buttonDeletePortal.addActionListener(e);
        buttonEdit.addActionListener(e);
        buttonEditPortal.addActionListener(e);
        buttonNewCard.addActionListener(e);
        buttonNewPortal.addActionListener(e);
        bBack.addActionListener(e);
    }
    public javax.swing.JButton getbBack() {
        return bBack;
    }
    public javax.swing.JTextField getTfIdPegawai() {
        return tfIdPegawai;
    }
    public javax.swing.JTextField getTfNamaPegawai() {
        return tfNamaPegawai;
    }
}
